name: ZAP Action

on:
  push:
    branches:
      - develop
jobs:
  build-and-test:
    name: Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run Vuln Node Express
        run: npm run start &
      - name: ZAP Scan
          continue-on-error: true
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:3000/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'